


ArticIndex:
  path: /artic/index.html.twig
  controller : App\Controller\ArticController::index




ArticCases:
  path: /artic/cases.html.twig
  controller: App\Controller\ArticController::cases
  methods:  [GET]